version: "3"

services:
  cppdev:
    hostname: cppdev
    container_name: cppdev
    build: .
    image: cppdev
    volumes:
      - ./dev:/root/dev
      - ./config/ssh:/root/.ssh
      - ./config/vscode-server:/root/.vscode-server
    ports:
      - "2222:22"
    cap_add:
      - "sys_ptrace"
